### ISSUE TITLE
Latest Appimage

### ISSUE THREAD

**Issue by Liverel** [TNTwise/REAL-Video-Enhancer-BETA#1]
The latest beta appimages doesn't launch at all for me; it just gives me an error message saying exec format error.

**Comment by TNTwise** [comment]
What distro are you on? The latest appimages need at least Ubuntu 22.04, also It might not package it correctly, as I'm using a different method, try installing qt as well. The error is very generic so please send a full output of the terminal

**Comment by Liverel** [comment]
> What distro are you on? The latest appimages need at least Ubuntu 22.04, also It might not package it correctly, as I'm using a different method, try installing qt as well. The error is very generic so please send a full output of the terminal

Using Arch, I am running the latest stable release of Plasma 6 desktop.

**Comment by TNTwise** [comment]
Can you send logs if they are available? They should be located at /home/$USER/.local/share/REAL-Video-Enhancer/logs/

**Comment by Liverel** [comment]
No log files there since the app doesn't launch at all in Dolphin File Manager. When I click the appimage, it says execve: Exec format error. When I try to launch the appimage from the terminal, all it says is ./REAL-Video-Enhancer-x86_64.AppImage: cannot execute binary file: Exec format error.

**Comment by TNTwise** [comment]
Is it executable? Is it extracted?

**Comment by Liverel** [comment]
It is executable, but it just doesn't work for some reason.

**Comment by Liverel** [comment]
The normal smaller appimage releases from Release 20240303-NCNN and Release 20240221 and before work fine.

**Comment by TNTwise** [comment]
Unfortunately, due to using a different packaging method because of how pytorch needs to be packaged, I am going to try to replicate the issue. I'm on Arch and it works fine so I'm assuming a missing dependency.

**Comment by TNTwise** [comment]
could possibly be fixed in latest build, please try again.

**Comment by Liverel** [comment]
[Screencast_20240310_071516.webm](https://github.com/TNTwise/REAL-Video-Enhancer-BETA/assets/62414119/7f105a7e-c276-43bc-ad21-1f6fc43d133a)

The Cuda appimages just doesn't work on my system for whatever reason.

**Comment by TNTwise** [comment]
You seem to have not copied the dependencies and just the executable, the app is packaged differently so it's not just one appimage anymore. 
Also, try downloading this version 
https://github.com/TNTwise/REAL-Video-Enhancer-BETA/releases/tag/2024038-CUDA

**Comment by Liverel** [comment]
Ah i see the latest cuda version launches now.
